### ISSUE TITLE
java.lang.IllegalStateException: No current assignment for partition

### ISSUE THREAD

**Issue by dr4ke616** [tenable/Kastle#171]
Seeing cases where the [`ConsumerStateHandler`](https://github.com/tenable/Kastle/blob/467ac11f8e8af3105cc5cb72ec2f93a28d84579e/src/main/scala/com/tenable/library/kafkaclient/client/standard/consumer/ConsumerStateHandler.scala#L140) is failing to get a current assignment for a partition. According to [this](https://stackoverflow.com/questions/54480715/no-current-assignment-for-partition-occurs-even-after-poll-in-kafka) we should be `seek`ing to the correct tp/offset, which we seem to be doing in the [`ExternalOffsetRebalanceListener`](https://github.com/tenable/Kastle/blob/467ac11f8e8af3105cc5cb72ec2f93a28d84579e/src/main/scala/com/tenable/library/kafkaclient/client/standard/consumer/ExternalOffsetRebalanceListener.scala).

Not totally sure why the issue still occurs, maybe just an artifact of some re-balancing. None-the-less, be nice to figure out exactly why its happening, and look to hanle this type of error more gracefully.

```
Failed refresh-temp-paused with error No current assignment for partition <partition-name>

java.lang.IllegalStateException: No current assignment for partition ...
    at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:368)
    at org.apache.kafka.clients.consumer.internals.SubscriptionState.resume(SubscriptionState.java:708)
    at org.apache.kafka.clients.consumer.KafkaConsumer.resume(KafkaConsumer.java:2043)
    at com.tenable.library.kafkaclient.client.standard.consumer.ConsumerStateHandler.$anonfun$refreshTemporarilyPaused$4(ConsumerStateHandler.scala:151)
...
```

**Comment by atnoya** [comment]
Would be curious to see what's going on...
I would say this feels like the partition was rebalanced before it was resumed, this might be as simple as checking if the partition that was paused, before resuming is still assigned to this consumer. That should be enough.

Also, I am surprised to see that you are using the ExternalOffsetRebalanceListener, happy it works for you, it was definitely not battle tested :)
